# Define the trigger for the pipeline, which specifies when it should run.
trigger:
- master

# Specify the agent pool and the VM image to use for running the pipeline.
pool:
  vmImage: 'ubuntu-latest'

# Define variables that can be used throughout the pipeline.
variables:
  buildConfiguration: 'Release'

# Define the list of jobs to execute as part of the pipeline.
jobs:
- job: BuildJob
  displayName: 'Build Job'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.102'

  - script: dotnet build --configuration $(buildConfiguration)
    workingDirectory: Backends/QandA
    displayName: 'backend build'

  - script: dotnet test
    workingDirectory: Backends/QandA
    displayName: 'backend tests'

  - script: dotnet publish -c $(buildConfiguration) --self-contained true -r win-x86
    workingDirectory: Backends/QandA
    displayName: 'backend publish'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Backends/QandA/bin/Release/net7.0/publish'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/Backends/QandA/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'backend zip files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'Backends/QandA'
      artifactName: 'backend'
    displayName: 'backend publish to pipeline'

  - script: npm install
    workingDirectory: Frontends/frontend
    displayName: 'frontend install dependencies'

  - script: npm run build:staging
    workingDirectory: Frontends/frontend
    displayName: 'frontend staging build'
    
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Frontends/frontend/build'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/build.zip'
      replaceExistingArchive: true
    displayName: 'frontend staging zip files'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Frontends/frontend/cypress'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/tests.zip'
      replaceExistingArchive: true
    displayName: 'frontend cypress zip files'  

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-staging'
      artifactName: 'frontend-staging'
    displayName: 'frontend staging publish to pipeline'

  - script: npm run build:production
    workingDirectory: Frontends/frontend
    displayName: 'frontend production build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Frontends/frontend/build'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-production/build.zip'
      replaceExistingArchive: true
    displayName: 'frontend production zip files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-production'
      artifactName: 'frontend-production'
    displayName: 'frontend production publish to pipeline'