# Define the trigger for the pipeline, which specifies when it should run.
trigger:
- master

# Specify the agent pool and the VM image to use for running the pipeline.
pool:
  vmImage: 'ubuntu-latest'

# Define variables that can be used throughout the pipeline.
variables:
  buildConfiguration: 'Release'

# Define the list of steps to execute as part of the pipeline.
  steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.102'

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: Backends/QandA
  displayName: 'backend build'